_format_version: "3.0"
_info:
  defaults: {}
  select_tags:
  - investment
_konnect:
  control_plane_name: default
services:
- connect_timeout: 60000
  enabled: true
  host: mocktainer.io
  name: InvestmentSvc
  path: /portfolio/v1
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: InvestmentRoute
    path_handling: v0
    paths:
    - /investment
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
