_format_version: "3.0"
_info:
  select_tags:
  - gitops
_konnect:
  control_plane_name: se-demo-rc-apiops
services:
- connect_timeout: 60000
  enabled: true
  host: jsonplaceholder.typicode.com
  name: JSONPlaceHolderDemoServiceSVC12
  path: /
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: JSONPlaceholderRoute
    path_handling: v0
    paths:
    - /jsonplaceholder
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
