name: Deploy Kong changes to Konnect

on:
  push:
    branches:
    - master
    paths:
    - config/kong/kong.yaml
    - .github/workflows/main.yaml

jobs:
  deploy_to_konnect:
    runs-on: ubuntu-latest
    name: Deploy Kong to Konnect
    environment: demo
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup deck
      uses: kong/setup-deck@v1
      with:
        deck-version: '1.29.2'
        wrapper: false
    - name: deck sync
      run: deck sync --select-tag investment -s config/kong/kong.yaml --konnect-control-plane-name default --konnect-token ${{ secrets.KONNECT_PAT }}
    
