name: Deploy Kong changes to Konnect

on:
  push:
    branches:
    - master
    paths:
    - config/kong/kong.yaml
    - .github/workflows/main.yaml

jobs:
  deploy_to_konnect:
    runs-on: ubuntu-latest
    name: Deploy Kong to Konnect
    environment: demo
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup deck
      uses: kong/setup-deck@v1
      with:
        deck-version: 'v1.42.1'
        wrapper: true
    - run: deck version
      id: deck_version
    - run: echo '${{ toJson(steps.deck_version.outputs) }}'
    - name: Add User-Defined Kong Rate Limiting Plugin
      run: |
        deck file add-plugins -s ./config/kong/kong.yaml -o kong.yaml ./config/kong/plugins/*
    - name: deck sync
      run: deck gateway sync --select-tag gitops config/kong/kong.yaml --konnect-addr https://au.api.konghq.com --konnect-control-plane-name se-demo-rc-apiops --konnect-token ${{ secrets.KONNECT_PAT }}
    
