name: Deploy Kong changes to Konnect

on:
  push:
    branches:
    - master
    paths:
    - config/kong/kong.yaml
    - .github/workflows/main.yaml
    paths-ignore:
    - README.md 

jobs:
    deploy-kong:
        name: Deploy Kong to Konnect
        runs-on: ubuntu-latest
        environment: demo
        steps:
        - name: Checkout
        uses: actions/checkout@v3
        - name: Setup deck
        uses: kong/setup-deck@v1
        with:
            deck-version: '1.29.2'
            wrapper: false
        - name: deck sync
        run: deck sync --select-tag investment -s config/kong/kong.yaml --konnect-control-plane-name default --konnect-token ${{ secrets.KONNECT_PAT }}